console.log("My first Console Project");
var first_name = "Aditya ";
var last_name = "Deshpande";
var con = first_name.concat(last_name);
var no1 = 12;
var no2 = 4;
var add = no1 + no2;
var sub = no1 - no2;
var multi = no1 * no2;
var div = no1/no2;
console.log(first_name);
console.log(last_name);
console.log(con);
console.log(no1);
console.log(no2);
console.log(add);
console.log(sub);
console.log(multi);
console.log(div);